### PR TITLE
Remove get and only allow getOrDefault

### PR DESCRIPTION
**Pull request by stevejhiggs**
get's a wee bit dangerous and allows people to treat toggles as tri-state. Lets be opinionated and stop that.

### CODE REVIEW

**Comment by ArnoldZokas** [comment]
+1

**Comment by johnnonolan** [comment]
I was just talking to @mattyod about Hobknob and noticed this. `getOrDefault` is better imho

**Comment by stevejhiggs** [comment]
Need an opinion from the rest of the team. I think I already offed get from the .net client.

**Comment by christriddle** [comment]
Lets get rid.

**Pull request closed without merging**
